### PR TITLE
Offload label filtering on cloudflare

### PR DESCRIPTION
**Pull request by axilleastr**
## Description

This PR aims to offload the label filtering on Cloudflare (addresses #2 ) and introduces the following changes:

*     feat: Offload label filtering on CloudFlare

    Currently, in order to find which DNS Records exist per cluster, we
    are fetching all TXT records from CloudFlare, and then we perform the
    label filtering on our side. This leads to quite expensive requests,
    since we don't really need to fetch all TXT records of our zone. We
    can optimise our queries to CloudFlare and reduce our code complexity
    by offloading the label filtering on the Cloudflare.
    This commit enables this functionality.

 *     chore: Upgrade cloudflare-go package to 0.35.1

      the cloudflare-go package we currently use, handles the api pagination internally. The specific version we are using has a statically defined per_page max records that can be retrieved, set to 100.
      
      This is removed on the newer releases, where the package uses the default per_page value as specified by the API. 
      
      This is visible here: https://github.com/cloudflare/cloudflare-go/compare/v0.15.0...master#diff-cb1b8a01bbc5f64cf06dce0e3f8021ad8289078b402dc620afa04780484d7cd5L74-L75
*     git: Ignore bin/ folder
## Test

Tested changes on a dev env, where casper-3 was able to successfully discover/create/delete new DNS records

### CODE REVIEW

**Review by hwoarang — APPROVED** [review]
That looks great but can you explain to me what `contains:` is supposed to do (where is this documented?) because I do not quite understand https://github.com/cloudflare/cloudflare-go/issues/613#issuecomment-813747784

**Review by atmosx — APPROVED** [review]
🏅

**Comment by axilleastr** [comment]
> That looks great but can you explain to me what `contains:` is supposed to do (where is this documented?) because I do not quite understand [cloudflare/cloudflare-go#613 (comment)](https://github.com/cloudflare/cloudflare-go/issues/613#issuecomment-813747784)

yes, it's not well documented and the only resource where i found that was this gh comment 😕 
I played with it and did tests locally, and saw that the dns records that this query returns are always the ones we need (it matches the filtered list of the records we currently filter within our code). However, the fact that it is not documented it may be a bit concerning 
let me dig a bit deeper and get back to you in case with a proper answer

**Comment by hwoarang** [comment]
@axilleastr the only reason I want to get to the bottom of this is that I am somewhat scared that this might be an undocumented API "feature" that may disappear at any point in the future

**Comment by hwoarang** [comment]
There is also some info here too https://github.com/cloudflare/terraform-provider-cloudflare/pull/708/files

**Comment by axilleastr** [comment]
> 

@hwoarang After some reading, concluded that the `contains` operator comes as part of the [ruleset-engine](https://developers.cloudflare.com/ruleset-engine/) Cloudflare feature. It is a nice way to enrich api requests to Cloudflare with a DSL style syntax (Rule expressions use a powerful Rules language similar to the wirefilter syntax that allows you to create complex rules)
More information about the language rules can be found [here](https://developers.cloudflare.com/ruleset-engine/rules-language/)
Having said that, I think that this explains this behavior and possibly eliminate the concerns we also have.

**Pull request merged**
